### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by icarito** [seanwu1105/ionic-pwa-example#167]
Hi,
I'm unable to build the project! Here's my logs output:
```
[icarito@tengu ionic-pwa-example]$ npm run serve

> moment@1.1.0 serve
> ionic serve

> ng run app:serve --host=localhost --port=8100
[ng] - Generating browser application bundles...
[ng] ✔ Browser application bundle generation complete.
[ng] Initial Chunk Files | Names         |    Size
[ng] main.js             | main          | 0 bytes
[ng] polyfills.js        | polyfills     | 0 bytes
[ng] runtime.js          | runtime       | 0 bytes
[ng] styles.js           | styles        | 0 bytes
[ng] vendor.js           | vendor        | 0 bytes
[ng] | Initial Total | 0 bytes
[ng] Build at: 2021-05-26T18:06:54.766Z - Hash: 6e7ce1dc1bb8447a1df4 - Time: 27364ms
[ng] Error: src/app/features/home/photo/photo.page.ts:114:30 - error TS2339: Property 'arrayBuffer' does not exist on type 'BlobBuffer'.
[ng]   Property 'arrayBuffer' does not exist on type 'Buffer'.
[ng] 114     switchMap(photo => photo.arrayBuffer()),
[ng]                                  ~~~~~~~~~~~
[ng] Error: src/app/features/home/photo/photo.page.ts:115:40 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'ArrayBuffer | Buffer | SharedArrayBuffer'.
[ng]   Type 'unknown' is not assignable to type 'SharedArrayBuffer'.
[ng] 115     map(arrayBuffer => ExifReader.load(arrayBuffer)),
[ng]                                            ~~~~~~~~~~~
[ng] Error: src/app/shared/moment/moment.ts:82:13 - error TS2322: Type 'BlobBuffer' is not assignable to type 'Blob'.
[ng]   Type 'Buffer' is missing the following properties from type 'Blob': size, type, arrayBuffer, stream, text
[ng] 82             image: await photo.getData(),
[ng]                ~~~~~
[ng]   src/app/utils/thumbnail.ts:7:3
[ng]     7   image: Blob;
[ng]         ~~~~~
[ng]     The expected type comes from property 'image' which is declared here on type '{ image: Blob; width: number; }'
[ng] Error: ./src/main.ts
[ng] Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
[ng] TypeError: validateOptions is not a function
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:71:5)
[ng]     at Generator.next (<anonymous>)
[ng]     at asyncGeneratorStep (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:3:103)
[ng]     at _next (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:194)
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:364
[ng]     at new Promise (<anonymous>)
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:97)
[ng]     at Object._loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:235:18)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:64:18)
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:59:12)
[ng] Error: ./src/polyfills.ts
[ng] Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
[ng] TypeError: validateOptions is not a function
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:71:5)
[ng]     at Generator.next (<anonymous>)
[ng]     at asyncGeneratorStep (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:3:103)
[ng]     at _next (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:194)
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:364
[ng]     at new Promise (<anonymous>)
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:97)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:64:18)
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:59:12)
[ng] Error: (webpack)-dev-server/client?http://0.0.0.0:0&sockPath=/sockjs-node
[ng] Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
[ng] TypeError: validateOptions is not a function
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:71:5)
[ng]     at Generator.next (<anonymous>)
[ng]     at asyncGeneratorStep (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:3:103)
[ng]     at _next (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:194)
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:364
[ng]     at new Promise (<anonymous>)
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:5:97)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:64:18)
[ng]     at Object.<anonymous> (/home/icarito/Proyectos/ionic-pwa-example/node_modules/babel-loader/lib/index.js:59:12)
[ng] Error: ./src/theme/variables.scss
[ng] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[ng] ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/webpack/lib/NormalModule.js:316:20
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[ng]     at context.callback (/home/icarito/Proyectos/ionic-pwa-example/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:104:7)
[ng] Error: ./src/global.scss
[ng] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[ng] ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/webpack/lib/NormalModule.js:316:20
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[ng]     at /home/icarito/Proyectos/ionic-pwa-example/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[ng]     at context.callback (/home/icarito/Proyectos/ionic-pwa-example/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:104:7)
[ng] Error: ./src/app/app.component.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/shared/copy-clipboard/copy-clipboard.component.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/shared/back-button/back-button.component.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/shared/image-viewer/image-viewer.page.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/features/home/home.page.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/shared/image/image.component.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/features/home/settings/settings.page.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/features/home/photo/photo.page.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/features/home/camera/camera.page.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)
[ng] Error: ./src/app/features/home/moment-thumbnail/moment-thumbnail.component.scss
[ng] Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
[ng] Error: PostCSS plugin postcss-import requires PostCSS 8.
[ng] Migration guide for end-users:
[ng] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[ng]     at Processor.normalize (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:167:15)
[ng]     at new Processor (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/processor.js:56:25)
[ng]     at postcss (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss/lib/postcss.js:55:10)
[ng]     at Object.loader (/home/icarito/Proyectos/ionic-pwa-example/node_modules/postcss-loader/dist/index.js:95:20)

[INFO] Development server running!
       
       Local: http://localhost:8100
       
       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!


```

**Comment by seanwu1105** [comment]
@icarito It should be fixed with 882a206cc98b10f8694587117d2ab0e0bb0646c3. If there are still issues on building, please let me know.

**Comment by icarito** [comment]
Thanks @seanwu1105  ! I'm still facing issues trying to build, this time missing `crypto` package, pointers welcome!
```
[ng] Build at: 2021-05-27T15:45:53.554Z - Hash: 3eb0769da2e5d0b50a3c - Time: 92544ms
[ng] Warning: ./node_modules/crypto-js/core.js
[ng] Module not found: Error: Can't resolve 'crypto' in '/home/icarito/Proyectos/ionic-pwa-example/node_modules/crypto-js'
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/jsonschema-key-compression/src/types.ts is part of the TypeScript compilation but it's unused.
[ng] Add only entry points to the 'files' or 'include' properties in your tsconfig.
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/jsonschema-key-compression/src/util.ts is part of the TypeScript compilation but it's unused.
[ng] Add only entry points to the 'files' or 'include' properties in your tsconfig.
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/jsonschema-key-compression/src/create-compression-table.ts is part of the TypeScript compilation but it's unused.
[ng] Add only entry points to the 'files' or 'include' properties in your tsconfig.
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/jsonschema-key-compression/src/compress.ts is part of the TypeScript compilation but it's unused.
[ng] Add only entry points to the 'files' or 'include' properties in your tsconfig.
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/jsonschema-key-compression/src/decompress.ts is part of the TypeScript compilation but it's unused.
[ng] Add only entry points to the 'files' or 'include' properties in your tsconfig.
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/jsonschema-key-compression/src/index.ts is part of the TypeScript compilation but it's unused.
[ng] Add only entry points to the 'files' or 'include' properties in your tsconfig.
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/src/app/utils/errors.ts is part of the TypeScript compilation but it's unused.
[ng] Add only entry points to the 'files' or 'include' properties in your tsconfig.
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/src/app/shared/extension/extension.pipe.ts depends on 'mime/lite'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/src/app/shared/moment/moment.ts depends on 'ua-parser-js'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/crypter.js depends on 'object-path'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/pouchdb-utils/lib/index-browser.es.js depends on 'immediate'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/rx-error.js depends on '@babel/runtime/helpers/wrapNativeSuper'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/rx-error.js depends on '@babel/runtime/helpers/inheritsLoose'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/rx-query.js depends on 'deep-equal'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/pouch-db.js depends on '@babel/runtime/regenerator'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/plugins/encryption.js depends on 'crypto-js/aes'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/plugins/encryption.js depends on 'crypto-js/enc-utf8'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/plugins/update.js depends on 'modifyjs'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Warning: /home/icarito/Proyectos/ionic-pwa-example/node_modules/rxdb/dist/es/plugins/validate.js depends on 'is-my-json-valid'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] Error: ./node_modules/rxdb/dist/es/rx-query.js 129:13-27
[ng] "export 'firstValueFrom' was not found in 'rxjs'
[ng] Error: ./node_modules/rxdb/dist/es/plugins/in-memory.js 145:11-25
[ng] "export 'firstValueFrom' was not found in 'rxjs'
[ng] Error: ./node_modules/rxdb/dist/es/plugins/replication.js 70:11-25
[ng] "export 'firstValueFrom' was not found in 'rxjs'
[ng] Error: ./node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js 3851:14-27
[ng] "export 'ɵRuntimeError' was not found in '@angular/core'
```

**Comment by seanwu1105** [comment]
@icarito Could you provide the environment to build the project? It seems the version of dependencies is wrong. For example, `firstValueFrom` should not exist in `rxjs: ^6.6.7`.

**Comment by seanwu1105** [comment]
Close due to inactivity.
